select 'DROP External Table ' + name  from sys.external_tables
 where name like 'TR_%'

DROP External Table TR_Org
DROP External Table TR_PolicyOrg
DROP External Table TR_LloydsBroker
DROP External Table TR_ApplicationUser
DROP External Table TR_PolicyLine
DROP External Table TR_PolicyLimit
DROP External Table TR_FinTransCategory
DROP External Table TR_PolicyDeduction
DROP External Table TR_FinTransCategoryRole
DROP External Table TR_PolicyPrem
DROP External Table TR_ReportingClass
DROP External Table TR_Policy
DROP External Table TR_ClaimStatus
DROP External Table TR_BusinessCode_new
DROP External Table TR_ClaimStatus_new
